-- Genera el volcado del esquema por secciones (jsonb). Instalar, usar y borrar:
--   select public._v2_dump();            -- esquema `public`
--   drop function public._v2_dump(text); -- al terminar
create or replace function public._v2_dump(p_schema text default 'public') returns jsonb
language plpgsql security definer set search_path = pg_catalog, pg_temp as $f$
declare
  ns oid := p_schema::regnamespace;
  r jsonb := '{}'::jsonb;
  t text;
begin
  select coalesce(string_agg(pg_get_functiondef(p.oid) || ';', E'\n\n' order by p.proname, pg_get_function_identity_arguments(p.oid)), '') into t
  from pg_proc p where p.pronamespace = ns and p.prokind in ('f','p')
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e');
  r := r || jsonb_build_object('functions', t);

  select coalesce(string_agg(
    format('create table %I.%I (', p_schema, c.relname) || E'\n' ||
    (select string_agg('  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
        || case when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(d.adbin, d.adrelid) || ') stored'
                when a.attidentity = 'a' then ' generated always as identity'
                when a.attidentity = 'd' then ' generated by default as identity'
                when d.adbin is not null then ' default ' || pg_get_expr(d.adbin, d.adrelid) else '' end
        || case when a.attnotnull then ' not null' else '' end, E',\n' order by a.attnum)
     from pg_attribute a left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
     where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped) || E'\n);',
    E'\n\n' order by c.relname), '') into t
  from pg_class c where c.relnamespace = ns and c.relkind in ('r','p');
  r := r || jsonb_build_object('tables', t);

  select coalesce(string_agg(format('alter table %I.%I add constraint %I %s;', p_schema, c.relname, k.conname, pg_get_constraintdef(k.oid)), E'\n' order by (k.contype = 'f'), c.relname, k.conname), '') into t
  from pg_constraint k join pg_class c on c.oid = k.conrelid where c.relnamespace = ns and k.contype in ('p','u','c','x','f');
  r := r || jsonb_build_object('constraints', t);

  select coalesce(string_agg(pg_get_indexdef(i.indexrelid) || ';', E'\n' order by ic.relname), '') into t
  from pg_index i join pg_class ic on ic.oid = i.indexrelid join pg_class tc on tc.oid = i.indrelid
  where tc.relnamespace = ns and not exists (select 1 from pg_constraint k where k.conindid = i.indexrelid);
  r := r || jsonb_build_object('indexes', t);

  select coalesce(string_agg(pg_get_triggerdef(g.oid) || ';' || case when g.tgenabled = 'D' then format(E'\nalter table %I.%I disable trigger %I;', p_schema, c.relname, g.tgname) else '' end, E'\n' order by c.relname, g.tgname), '') into t
  from pg_trigger g join pg_class c on c.oid = g.tgrelid where c.relnamespace = ns and not g.tgisinternal;
  r := r || jsonb_build_object('triggers', t);

  select coalesce(string_agg(
    format('alter table %I.%I enable row level security;', p_schema, c.relname)
    || case when c.relforcerowsecurity then format(E'\nalter table %I.%I force row level security;', p_schema, c.relname) else '' end
    || case when c.relreplident = 'f' then format(E'\nalter table %I.%I replica identity full;', p_schema, c.relname) else '' end,
    E'\n' order by c.relname), '') into t
  from pg_class c where c.relnamespace = ns and c.relkind in ('r','p') and (c.relrowsecurity or c.relreplident = 'f');
  r := r || jsonb_build_object('rls', t);

  select coalesce(string_agg(format('create policy %I on %I.%I as %s for %s to %s%s%s;', pol.policyname, p_schema, pol.tablename, lower(pol.permissive), lower(pol.cmd),
      array_to_string(pol.roles, ', '),
      case when pol.qual is not null then ' using (' || pol.qual || ')' else '' end,
      case when pol.with_check is not null then ' with check (' || pol.with_check || ')' else '' end), E'\n' order by pol.tablename, pol.policyname), '') into t
  from pg_policies pol where pol.schemaname = p_schema;
  r := r || jsonb_build_object('policies', t);

  select coalesce(string_agg(x.stmt, E'\n' order by x.ord), '') into t from (
    select c.relname || '0' as ord, format('revoke all on table %I.%I from anon, authenticated, service_role;', p_schema, c.relname) as stmt
      from pg_class c where c.relnamespace = ns and c.relkind in ('r','p')
    union all
    select c.relname || '1' || g.rolname, format('grant %s on table %I.%I to %I;', string_agg(a.privilege_type, ', ' order by a.privilege_type), p_schema, c.relname, g.rolname)
      from pg_class c cross join lateral aclexplode(coalesce(c.relacl, acldefault('r', c.relowner))) a join pg_roles g on g.oid = a.grantee
      where c.relnamespace = ns and c.relkind in ('r','p') and g.rolname in ('anon','authenticated','service_role')
      group by c.relname, g.rolname
    union all
    select c.relname || '2' || at.attname || g.rolname, format('grant %s (%I) on table %I.%I to %I;', string_agg(a.privilege_type, ', ' order by a.privilege_type), at.attname, p_schema, c.relname, g.rolname)
      from pg_class c join pg_attribute at on at.attrelid = c.oid and at.attacl is not null and at.attnum > 0 and not at.attisdropped
      cross join lateral aclexplode(at.attacl) a join pg_roles g on g.oid = a.grantee
      where c.relnamespace = ns and c.relkind in ('r','p') and g.rolname in ('anon','authenticated','service_role')
      group by c.relname, at.attname, g.rolname
  ) x;
  r := r || jsonb_build_object('grants_tables', t);

  select coalesce(string_agg(x.stmt, E'\n' order by x.ord), '') into t from (
    select p.proname || pg_get_function_identity_arguments(p.oid) || '0' as ord,
      format('revoke all on function %I.%I(%s) from public, anon, authenticated, service_role;', p_schema, p.proname, pg_get_function_identity_arguments(p.oid)) as stmt
      from pg_proc p where p.pronamespace = ns and p.prokind in ('f','p') and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
    union all
    select p.proname || pg_get_function_identity_arguments(p.oid) || '1' || coalesce(g.rolname, 'public'),
      format('grant execute on function %I.%I(%s) to %s;', p_schema, p.proname, pg_get_function_identity_arguments(p.oid), coalesce(quote_ident(g.rolname), 'public'))
      from pg_proc p cross join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) a left join pg_roles g on g.oid = a.grantee
      where p.pronamespace = ns and p.prokind in ('f','p') and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
        and (a.grantee = 0 or g.rolname in ('anon','authenticated','service_role'))
  ) x;
  r := r || jsonb_build_object('grants_functions', t);

  select coalesce(string_agg(format('alter publication %I add table %I.%I;', pt.pubname, p_schema, pt.tablename), E'\n' order by pt.pubname, pt.tablename), '') into t
  from pg_publication_tables pt where pt.schemaname = p_schema and pt.pubname = 'supabase_realtime';
  r := r || jsonb_build_object('publications', t);

  select coalesce(string_agg(format('%I.%I', p_schema, c.relname), ', '), '') into t
  from pg_class c where c.relnamespace = ns and c.relkind = 'S' and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype in ('a','i'));
  r := r || jsonb_build_object('loose_sequences', t);
  return r;
end $f$;
revoke all on function public._v2_dump(text) from public, anon, authenticated;
